<?xml version="1.0"?>
<!--DOCTYPE page SYSTEM "PageSchema.dtd"-->
<!DOCTYPE pages [
<!ELEMENT pages (page+)>
<!ELEMENT page ANY>

<!ELEMENT text (content+, text*)>
<!ATTLIST text id CDATA "0">
<!ATTLIST text font CDATA "Arial">
<!ATTLIST text fontStyle CDATA "Normal">
<!ATTLIST text fontSize CDATA "16">
<!ATTLIST text lineSpace CDATA "0">
<!ATTLIST text positionX CDATA "0">
<!ATTLIST text positionY CDATA "0">
<!ATTLIST text positionZ CDATA "0">
<!ATTLIST text scaleX CDATA "1">
<!ATTLIST text scaleY CDATA "1">
<!ATTLIST text scaleZ CDATA "1">
<!ATTLIST text rotationX CDATA "0">
<!ATTLIST text rotationY CDATA "0">
<!ATTLIST text rotationZ CDATA "0">
<!ELEMENT content (#PCDATA)>

<!ELEMENT image (source, description?)>
<!ELEMENT source EMPTY>
<!ELEMENT description (#PCDATA)>
<!ATTLIST image id CDATA "0">
<!ATTLIST source href CDATA #REQUIRED>
<!ATTLIST image positionX CDATA "0">
<!ATTLIST image positionY CDATA "0">
<!ATTLIST image positionZ CDATA "0">
<!ATTLIST image scaleX CDATA "1">
<!ATTLIST image scaleY CDATA "1">
<!ATTLIST image scaleZ CDATA "1">
<!ATTLIST image rotationX CDATA "0">
<!ATTLIST image rotationY CDATA "0">
<!ATTLIST image rotationZ CDATA "0">

<!ELEMENT video (source, description?)>
<!ATTLIST video id CDATA "0">
<!ATTLIST video positionX CDATA "0">
<!ATTLIST video positionY CDATA "0">
<!ATTLIST video positionZ CDATA "0">
<!ATTLIST video scaleX CDATA "1">
<!ATTLIST video scaleY CDATA "1">
<!ATTLIST video scaleZ CDATA "1">
<!ATTLIST video rotationX CDATA "0">
<!ATTLIST video rotationY CDATA "0">
<!ATTLIST video rotationZ CDATA "0">

<!ELEMENT model (source, description?)>
<!ATTLIST model id CDATA "0">
<!ATTLIST model height CDATA "0" width CDATA "0">
<!ATTLIST model positionX CDATA "0">
<!ATTLIST model positionY CDATA "0">
<!ATTLIST model positionZ CDATA "0">
<!ATTLIST model scaleX CDATA "1">
<!ATTLIST model scaleY CDATA "1">
<!ATTLIST model scaleZ CDATA "1">
<!ATTLIST model rotationX CDATA "0">
<!ATTLIST model rotationY CDATA "0">
<!ATTLIST model rotationZ CDATA "0">
]>

<pages>
	<page>
		<text id="0">
			<content>Hello my name is Albert</content>
		</text>
		<text id="1" font="DIN RegularAlternate" fontStyle="Regular" fontSize="8" lineSpace="15" positionY="50">
			<content>
		    Hello my name is Keefe.
		    I am currently studying Computer Science.
		    </content>
		</text>
		<image id="2" scaleX="0.3" scaleY="0.3" scaleZ="0.3" positionY="120" positionX="200">
			<source href="Assets/Resources/Images/image1.jpg"></source>
			<description>Picture of Albert</description>
		</image>
		<model id="3" scaleX="4000" scaleY="4000" scaleZ="4000" positionX="-200" positionY="50" rotationX="-30">
			<source href="Models/Glass"></source>
			<description>Load model 1</description>
		</model>
		<model id="4" scaleX="30" scaleY="30" scaleZ="30" positionX="30" positionY="-100" positionZ="-100">
			<source href="Models/Lemon Whole"></source>
			<description>Load model 1</description>
		</model>
		<image id="5" scaleX="0.1" scaleY="0.1" scaleZ="0.1" positionY="-150" positionX="-250">
			<source href="Assets/Resources/Images/Lo-Fi CZ3003-04.jpg"></source>
			<description>Picture of Albert</description>
		</image>
		<video id="6" rotationX="90" rotationY="180" positionZ="-10" positionX="200" positionY="-150" scaleX="20" scaleZ="20">
			<source href="Resources/Videos/Video2.ogv"> </source>
			<description>Video of Albert</description>
		</video>
		<text id="7" fontSize="20" positionX="-300" positionY="200">
			<content>This is page 1</content>
		</text>
	</page>
	<page>
		<image id="0" scaleX="0.3" scaleY="0.3" scaleZ="0.3" positionY="-150" positionX="-200">
			<source href="Assets/Resources/Images/Image1.jpg"></source>
			<description>Picture of Albert</description>
		</image>
		<model id="1" scaleX="4000" scaleY="4000" scaleZ="4000" positionX="200">
			<source href="Models/Glass"></source>
			<description>Load model 1</description>
		</model>
		<model id="2" scaleX="50" scaleY="50" scaleZ="50" positionX="-200" positionY="100">
			<source href="Models/Lemon Whole"></source>
			<description>Load model 1</description>
		</model>
		<video id="3" rotationX="90" rotationY="180" positionZ="-10" positionY="100" scaleX="20" scaleZ="20">
			<source href="Resources/Videos/Yee.ogv"> </source>
			<description>Video of Albert</description>
		</video>
		<text id="6" fontSize="20" positionX="-300" positionY="200">
			<content>This is page 2</content>
		</text>
	</page>
	<page>
		<text id="0" positionX="-250" positionY="150">
			<content>Hello my name is Albert</content>
		</text>
		<text id="1" font="DIN RegularAlternate" fontStyle="Regular" fontSize="8" lineSpace="15" positionX="-250" positionY="100">
			<content>
		    Hello my name is Keefe.
		    I am currently studying Computer Science.
		    </content>
		</text>
		<text id="2" positionX="-250" positionY="50">
			<content>
			Working on this URECA project.
			Someone said they lived together,
			I ran out the door to get her.
			</content>
		</text>
		<text id="3" font="DIN RegularAlternate" fontStyle="Regular" fontSize="8" lineSpace="15" positionX="-150">
			<content>
		    Given your question "is it possible", almost everything is possible.
		    Probably your are doing a basic error.
		    </content>
		</text>
		<text id="4" fontSize="20" positionX="-300" positionY="200">
			<content>This is page 3</content>
		</text>
	</page>
</pages>
