<?xml version="1.0"?>
<!--DOCTYPE page SYSTEM "PageSchema.dtd"-->
<!DOCTYPE page [
<!ELEMENT page ANY>

<!ELEMENT text (content+, text*)>
<!ATTLIST text id ID #IMPLIED fontFamily CDATA "Helvetica">
<!ATTLIST text fontStyle CDATA "Regular">
<!ATTLIST text fontSize CDATA "16">
<!ATTLIST text kerning CDATA "0">
<!ATTLIST text lineSpace CDATA "0">
<!ATTLIST text top CDATA "0">
<!ATTLIST text bottom CDATA "0">
<!ATTLIST text left CDATA "0">
<!ATTLIST text right CDATA "0">
<!ELEMENT content (#PCDATA)>

<!ELEMENT image (source, description?)>
<!ELEMENT source EMPTY>
<!ELEMENT description (#PCDATA)>
<!ATTLIST image id ID #IMPLIED>
<!ATTLIST image height CDATA "0">
<!ATTLIST image width CDATA "0">
<!ATTLIST image top CDATA "0">
<!ATTLIST image bottom CDATA "0">
<!ATTLIST image left CDATA "0">
<!ATTLIST image right CDATA "0">
<!ATTLIST source href CDATA #REQUIRED>

<!ELEMENT video (source, description?)>
<!ATTLIST video id ID #IMPLIED>
<!ATTLIST video height CDATA "0" width CDATA "0">
<!ATTLIST video top CDATA "0">
<!ATTLIST video bottom CDATA "0">
<!ATTLIST video left CDATA "0">
<!ATTLIST video right CDATA "0">

<!ELEMENT model (source, description?)>
<!ATTLIST model id ID #IMPLIED>
<!ATTLIST model height CDATA "0" width CDATA "0">
<!ATTLIST model top CDATA  "0">
<!ATTLIST model bottom CDATA  "0">
<!ATTLIST model left CDATA  "0">
<!ATTLIST model right CDATA  "0">
]>

<page>
	<text>
		<content>Hello my name is Albert</content>
	</text>
	<text fontFamily="Avenir Next" fontStyle="Regular" fontSize="8" kerning="0" lineSpace="15">
		<content>I am currently studying Computer Science</content>
	</text>
	<image height="10" width="5" top="2" bottom="2" left="1" right="1">
		<source href="https://www.smashingmagazine.com/wp-content/uploads/2015/06/10-dithering-opt.jpg"> </source>
		<description>Picture of Albert</description>
	</image>
	<video height="15" width="30">
		<source href="http://www.vid456.com/"> </source>
		<description>Video of Albert</description>
	</video>
</page>

